import { User, Transaction, LoyaltyReward } from '../types';

export const mockUser: User = {
  id: '1',
  matricNumber: '18CSC001',
  firstName: 'Sarah',
  lastName: 'Johnson',
  email: 'sarah.johnson@stu.cu.edu.ng',
  balance: 15750,
  loyaltyPoints: 1250,
  level: 'Gold Brew',
  createdAt: new Date().toISOString(),
};

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    type: 'payment',
    amount: 2500,
    description: 'Cafeteria - Lunch',
    recipient: 'CU Cafeteria',
    date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    pointsEarned: 25,
  },
  {
    id: '2',
    type: 'received',
    amount: 5000,
    description: 'Top-up from parent',
    sender: 'External Source',
    date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
  },
  {
    id: '3',
    type: 'transfer',
    amount: 1500,
    description: 'Transfer to friend',
    recipient: '19CSC045',
    date: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    pointsEarned: 15,
  },
  {
    id: '4',
    type: 'payment',
    amount: 800,
    description: 'Bookstore - Stationery',
    recipient: 'CU Bookstore',
    date: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    pointsEarned: 8,
  },
  {
    id: '5',
    type: 'reward',
    amount: 500,
    description: 'Weekly activity bonus',
    date: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    pointsEarned: 50,
  },
];

export const loyaltyRewards: LoyaltyReward[] = [
  {
    id: '1',
    title: 'First Brew',
    description: 'Complete your first transaction',
    pointsRequired: 10,
    icon: 'coffee',
    unlocked: true,
  },
  {
    id: '2',
    title: 'Tea Novice',
    description: 'Earn 100 loyalty points',
    pointsRequired: 100,
    icon: 'award',
    unlocked: true,
  },
  {
    id: '3',
    title: 'Steeping Strong',
    description: 'Complete 20 transactions',
    pointsRequired: 500,
    icon: 'trending-up',
    unlocked: true,
  },
  {
    id: '4',
    title: 'Tea Master',
    description: 'Earn 1000 loyalty points',
    pointsRequired: 1000,
    icon: 'crown',
    unlocked: true,
  },
  {
    id: '5',
    title: 'Golden Leaf',
    description: 'Reach Gold Brew level',
    pointsRequired: 2000,
    icon: 'sparkles',
    unlocked: false,
  },
  {
    id: '6',
    title: 'Campus Legend',
    description: 'Complete 100 transactions',
    pointsRequired: 5000,
    icon: 'trophy',
    unlocked: false,
  },
];
